### ISSUE TITLE
xpemon: add a mouse tracker on the plots

### ISSUE THREAD

**Issue by csgro** [lucabaldini/xpedaq#108]
It would be nice to have info on the x,y,z on the plot when the mouse is over a plot.

**Comment by albertomanfreda** [comment]
Done for the 1d histograms. It is displayed on top of the mouse cursor whenever it is positioned above a plot.

**Comment by albertomanfreda** [comment]
the mouse tracker is displayed incorrectly on windows systems (too much space between the numbers)

**Comment by albertomanfreda** [comment]
The mouse tracker is cutted when close to the right edge of the plot window. Also, it is difficult to make it visible on the 2D color map. A solution would be to leave a margin below the plots and put the info there (ROOT-like).

**Comment by albertomanfreda** [comment]
We have the mouse tracker up and running everywhere, now.
