### ISSUE TITLE
Add a mouse event to reset the pedestal plots

### ISSUE THREAD

**Issue by csgro** [lucabaldini/xpedaq#115]
It is annoying that once you have zoomed you cannot go back to the initial condition.

**Comment by albertomanfreda** [comment]
There is now a button for restoring the initial view (only for the 2d plots). In the future we may want to have separate buttons, maybe accessible by right clicking on the plot.

**Comment by albertomanfreda** [comment]
This apply also to the monitor, btw.

**Comment by albertomanfreda** [comment]
It is now possible to restore each plot (regardless of the application) to its initial view by right clicking on it and pressing a button in a pop-up menu. The former restore button in the pedestal application has been removed.
