### ISSUE TITLE
add barycenter map and average in the monitor

### ISSUE THREAD

**Issue by albertomanfreda** [lucabaldini/xpedaq#124]

**Comment by albertomanfreda** [comment]
Do we still want a barycenter 2D map? (I don't even remember what 'average' actually means here).

**Comment by lucabaldini** [comment]
Are we sure we still want this? Alberto?

**Comment by albertomanfreda** [comment]
We have mentioned the possibility to include a map of the impact points. Anyway, I think this issue is not relevant anymore.
