### ISSUE TITLE
The monitor should be able to cut on the event quality for the single-event display tab

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/xpedaq#134]
Initially we want to be able to cut on 
- the ratio between the longitudinal and transverse moments
- the size of the event window
- the pulse height

**Comment by lucabaldini** [comment]
additional cuts should be on:
- min/max window size
- min number of pixels in a cluster

**Comment by albertomanfreda** [comment]
We now have a rich interface of cuts at disposal. Closing.
