### ISSUE TITLE
push button icons disappeared in my pc

### ISSUE THREAD

**Issue by csgro** [lucabaldini/xpedaq#21]
I can't see anymore the icons on all the push buttons. 
Not sure what is the case. It happened while I was playing with the QuickUSB interface, but it may be by chance.
Working on fedora23 64bits.

**Comment by csgro** [comment]
Reason found in XPOL_DAQ_ROOT not set in the daq code dir, but in another one containing only the .cfg files.
It this a feature or a bug?

**Comment by lucabaldini** [comment]
Well, that was the way the code was designed to work.

If we can find out at run time where a file lives (a la Python) we can get away without an environmental variable. I am not sure what the most common way to do this is.

**Comment by csgro** [comment]
Fine. If that's a feature, let's close this issue.

**Comment by lucabaldini** [comment]
Done.
