### ISSUE TITLE
Make the event timestamp (kind of) absolute

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/xpedaq#33]
We don't have a GPS and all we can add is an offset determined by the local time of the acquisition PC at the start run, but this will be adequate to cross correlate with the environmental conditions.

**Comment by lucabaldini** [comment]
(And eventually this will be made at the FPGA level, but for the time being the quick and dirty solution is to have the DAQ do it after the fact.)

**Comment by csgro** [comment]
This is related to #41, where the data structure is described.
We currently use 2 unsigned short, that combined, give us the time from the start in milliseconds. In the current reconstruction these number are combined in a "(Double_t)(time1 + time2_65534)_0.8; //in microsec" which create several rollover. Not sure where the 0.8 comes from, but clearly 2**32 us = 1.19 hours are not enough!
The following 2 unsigned short are not used and can be assigned to event time (in a way TBD), even one ushort would be enough to cover ~9 year timespan with us resolution.

**Comment by lucabaldini** [comment]
The number of seconds since January 1, 1970 (unix timestamp) at the beginning of the run is now added by the daq in the 4 unused bytes 16--20. (Mind it's the same for all the events in a run.)

It can be parsed in the same fashion the microseconds are. Just add it to the us and we have a sensible absolute timestamp.

**Comment by csgro** [comment]
Looks like we killed the time stamp byte (the two 16-bit counters ) that are now 0. 
Here the dump of the first event in run 002_000014:
header 65535 True
Roi 160
Roi 185
Roi 110
Roi 133
numPix= 624
bufferID= 0
-----> times 0 0 0.0 <--------- print "times", time1, time2, timestamp
dummy 22304 39425
total bytes red:  1268

**Comment by lucabaldini** [comment]
It turns out this was a bug in the DAQ since the very beginning, due to a wrong initialization of the sequencer. Single-line fix:

```
 int pUsbController::startSequencer()
 {
   *xpollog::kInfo << "Starting QuickUsb sequencer..." << endline;
-  unsigned char value[1] = {0xf5};
+  unsigned char value[1] = {0xc5};
   return writePort(PORTC, value, 1);
 }
```
