### ISSUE TITLE
Fix the compilation for Linux 64 bits

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/xpedaq#4]
```
/usr/bin/ld: cannot find -lquickusb
collect2: error: ld returned 1 exit status
Makefile:221: recipe for target 'xpol' failed 
make: *** [xpol] Error 1
```

**Comment by lucabaldini** [comment]
Ok, first of all there's no real issue here, as stated on
http://www.bitwisesys.com/category-s/1830.htm

QuickUSB is supported on x86 and x64 versions of: Windows XP, Windows Vista, Windows 7, Linux (kernel v2.6.25 and later), and Mac OS X (v10.6 and later). There is limited support for Linux running older than kernel v2.6.25--specifically, asynchronous IO may not be supported.

There's two ways to go about this:

1\ Compile against the x64 library on Linux (and Windows?) machines running 64-bit OS. This is straightforward, although there's a couple of tweaks to do wrt our current setup, namely (i) QuickUsb.h is now called QuickUSB.h and (ii) CQuickUsb::IsOpen() is now called CQuickUsb::IsOpened(), which in turns requires two edits in daq/pRunController.cpp.

2\ Compile against the x86 library even on 64-bit systems. This can be done by installing the necessary .i686 libraries (qt-devel.i686 and glibc-devel.i386 on Fedora), using the 32-bit version of qmake

```
use /usr/lib/qt4/bin/qmake
```

and add the -m32 to LFLAGS in the Makefile (I also had to soft-link the libquickus shared object for the linker to find it). Presumably this can be all automated, if we need to.

I verified that 1\ works on Melissa's laptop (running Fedora 23 x64, and Michael did the same on SL 6). Carmelo reports that 2\ works on his laptop as well (again, Fedora 23 x64). On a related note, I succesfully compiled the DAQ on my laptop (Fedora 20 x64) both ways, but in both cases the DAQ segfaults at the very beginning. At this point I am willing to accept that there's something funky in my setup and move on---I am updating the OS in the next few days anyway.

**Comment by lucabaldini** [comment]
And, just for completeness, we have to decide which way we want to go. Needless to say, I vote for 1.

**Comment by lucabaldini** [comment]
For what it's worth, this is clearly related to issue #15.

**Comment by csgro** [comment]
"(i) QuickUsb.h is now called QuickUSB.h" rally means you have to change one include in daq/pUsbController.h

**Comment by lucabaldini** [comment]
We now have at least one machine where we have compiled against the new (2.15.2) 64-bit library for Linux, see issue #15 

If we decide to stick to this version of the library we can close this one.

**Comment by lucabaldini** [comment]
I'd say we close this one, although issue #15 is still open (but that's not specific to 64 bits.)
