### ISSUE TITLE
Check coordinate systems

### ISSUE THREAD

**Issue by csgro** [lucabaldini/xpedaq#72]
The ASIC is asymmetric with a long side (352 pixels) and a short one (300 pixels). And we have 2 conventions around for what we call X and Y. In the recon software the X side is the long one, but in old DAQ and monitor, X is the short side. 
In this xpedaq X seems to be the long one:
   daq/xpoldetector.cpp:unsigned short int xpoldetector::kNumPixelsX = 352;
Need to make sure we follow the same convention when we set the strobed channel for charge injection and trigger mask.

**Comment by csgro** [comment]
This morning I did a few quick charge injection runs changing the X,Y pixel and looking for the one with highest charge in the output (expect for a few noisy pixels in the ASIC I used). The output binary file is parsed assuming Recon convention. Here the result (station ID 33):

Id - X Y - X Y recon
47 - 50 50 - 50 52
48 - 55 50 - 50 57
49 - 60 50 - 50 62
50 - 100 50 - 50 102
51 - 50 55 - 55 52
52 - 50 60 - 60 52
53 - 50 100 - 100 52

We can conclude that we are mixing conventions in the daq gui: 
Y in gui is actually X in recon and X in gui is Y in recon +2

The addressing is done in the function
 `void pXpolFpga::writeAddress(unsigned short X, unsigned short Y)`
Need to decode the calls to serialWrite and undestand the origin of +2

**Comment by csgro** [comment]
A note on the ASIC and RECON reference system. 

ASIC reference system:

> Length, in pixels, of X is 300 and Y is 352; (0,0) is top left and (299,352) is bottom right.
> ROI word is Xmin, Xmax, Ymin, Ymax
> ROI is read in line by line from left to right and top to bottom (i.e. for (ix...){ for (iy..) {...}} )

RECON reference system tries to be similar to orientation of plotting tools, and keeps (0,0) on lower left corner

> Length, in pixels, of X is 352 and Y is 300; (0,0) is bottom left and (299,352) is top right.
> ROI word is Ymin, Ymax, Xmin, Xmax
> ROI is read in columns bottom to top and from left to right (i.e. for (iy...){ for (ix..) {...}} )

In practice RECON system obtained with a counterclockwise 90deg rotation of the ASIC system: 
Yrecon = Xasic and Xrecon = Yasic

**Comment by lucabaldini** [comment]
Try to swap X and Y in pXpolFpga::writeAddress, it half worked: no way to fix the +2 offset.

**Comment by csgro** [comment]
Try to swap X and Y in pXpolFpga::writeAddress, it half worked: no way to fix the +2 offset.
For some reasons I don't understand the second bit is changed somewhere...

Needless to say that when the index is larger than max number of pixels -2, the address is nonsense.

**Comment by csgro** [comment]
Tested with "old" DAQ and all is fine: injected pixel (10,100) in ASIC ref. system and got (100,10) in RECON ref. system as expected.

**Comment by lucabaldini** [comment]
The +2 shift has nothing to do with the coordinate system and is now tracked in issue #79.

**Comment by lucabaldini** [comment]
Note this issue also applies to the python lib.

**Comment by lucabaldini** [comment]
For the DAQ we will use the ASIC reference system as described in the XPOL document. pyxpe is up to speed.
